require('basic')
require('keybindings')
require('plugins')
require('colortheme')
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
-- require("plugin-config.copilot")
require("plugin-config.nvim-autopairs")
require("lsp.setup")
require("lsp.cmp")

